### ISSUE TITLE
react-native implementation

### ISSUE THREAD

**Issue by tex0l** [seald/sscrypto#4]
To provide a react-native implementation, we plan to use [react-native-cryptopp](https://github.com/JiriHoffmann/react-native-cryptopp). However, it is currently unstable and has limitations that prevent its implementation.

Library-wide issues:
- [ ] Repair the repo (in general) https://github.com/JiriHoffmann/react-native-cryptopp/issues/14
- [ ] Repair the build for iOS https://github.com/JiriHoffmann/react-native-cryptopp/issues/15
- [ ] I/O as `ArrayBuffer` that contains binary https://github.com/JiriHoffmann/react-native-cryptopp/issues/5
- [ ] repair name of hash functions https://github.com/JiriHoffmann/react-native-cryptopp/issues/20

RSA issues:
- [ ] Assess that generation works
  - [ ] Allow to modify the public exponent (currently 17, it needs to be 65537) https://github.com/JiriHoffmann/react-native-cryptopp/issues/18
- [ ] Assess that encryption works
  - [x] assess that RSA-OAEP-SHA1-MGF1 is compatible to / from `sscrypto/forge` with UTF8 strings
  - [ ] assess that RSA-OAEP-SHA1-MGF1 is compatible to / from `sscrypto/forge` with ArrayBuffers
  - [ ] implement CRC32 https://github.com/JiriHoffmann/react-native-cryptopp/issues/19
- [ ] Assess that signature works
  - [ ] Repair RSA-PSSR signature, implement RSA-PSS signature and verification & allow modifying the salt length https://github.com/JiriHoffmann/react-native-cryptopp/issues/17
  - [x] assess that, once repaired, RSA-PSS signature & verification of UTF8 string works
  - [ ] assess that, once repaired, RSA-PSS signature & verification of ArrayBuffers works

AES issues:
- [x] assess that AES-CBC works with 256 bits keys and utf8strings
- [ ] assess that AES-CBC works with 256 bits keys and binary data in an ArrayBuffer

HMAC issues:
- [x] assess that HMAC works in one call with an UTF8 string
- [ ] assess that HMAC works in one call with an ArrayBuffer
- [ ] assess that HMAC works step by step with an ArrayBuffer https://github.com/JiriHoffmann/react-native-cryptopp/issues/9

**Comment by mfbx9da4** [comment]
Is it worth tracking iOS app extension compatibility as well here?

**Comment by tex0l** [comment]
@mfbx9da4 I don't think an iOS app extension will be solved through an optimized version of sscrypto in JS. It needs to be native code directly, we'll solve this through the native implementation of the SDK.
